# Generated by Django 2.0.6 on 2019-05-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190523_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
