# Generated by Django 2.0.6 on 2019-05-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190522_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
