# Generated by Django 2.0.6 on 2019-05-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190524_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
