# Generated by Django 2.0.6 on 2019-05-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_post_total_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
